### ISSUE TITLE
请教如何保存在Shell中

### ISSUE THREAD

**Issue by mingde816** [miaowm5/KeUploader#1]
Thanks，非常适合小白，经实验已成功。
请教如何在自己的GoogleCloudPlatform中保存以上代码，每次都要复制么

**Comment by miaowm5** [comment]
具体来说你是要保存哪段代码呢？
基本上，成功部署一次之后，之后 KindleEar 在 Git 上更新时只要在 shell 里输入

``` shell
cd KeUploader
sh upload.sh
```

就可以自动更新GAE上 KindleEar 到最新的版本了
（除非 git 地址也换了……）

**Comment by mingde816** [comment]
貌似是这样的，用你的没问题。
因为我想上传我自己的KindleEar，有些自定义的图书等等
把你的fork过去之后，修改了一下upload.sh里面的地址，但上传就出错了。。。
本来想把您的这个代码保存到Shell里面去，
git clone https://github.com/miaowm5/KeUploader.git  →改为自己的
cd KeUploader
sh upload.sh

**Comment by miaowm5** [comment]
也许是提示目录已存在无法 git clone 报错？
先执行

``` shell
rm -rf KeUploader
```

然后再试试？

或者截图一下报错内容……

**Comment by mingde816** [comment]
谢谢，这下貌似成功了。
也就是说这个SHELL不管在哪个项目中都可以运行么貌似也没有日志。

**Comment by miaowm5** [comment]
好像是，shell 存储的文件不和项目绑定的感觉？
其实我也是昨天才开始用不是很懂……
