### ISSUE TITLE
求救。。。无法推送

### ISSUE THREAD

**Issue by mingde816** [miaowm5/KeUploader#2]
大神你好，不知道是不是巧合，昨天通过Shell上传成功了版本1.23.2，（原来版本1.22）
但是无论是自动还是手动推送，都是无法推送。
日志里也没有。。。。
该从哪里排查。。。转发器用自带的也无果。。。

![image](https://cloud.githubusercontent.com/assets/7845927/15696055/97811614-27df-11e6-8d45-4388bca91910.png)

**Comment by mingde816** [comment]
以下的错误日志出现在昨天上传完之后，是KindleEar版本的问题吗
![image](https://cloud.githubusercontent.com/assets/7845927/15696818/c830e49a-27e6-11e6-9781-5fc00695985f.png)

**Comment by miaowm5** [comment]
能点开那个 log 看一下详情吗？
另外 Work 模块的日志都是正常的吗？

以及我稍微有点没看懂你截图里的推送日志是什么情况……其中一个用户无法推送？

**Comment by mingde816** [comment]
你好，抱歉，容我叙述不太明白。
是有两个用户，不过都是停止在了5/31，我是想表达6/1日没有自动推送，而且手动推送了很多次，日志都没有显示。。。
我把Work模块的日志截图如下
![image](https://cloud.githubusercontent.com/assets/7845927/15703113/49560260-2816-11e6-853d-7288c5371a83.png)

最后参考你之前的#291 解决方案，下载 GAE python 和 SocksiPy之后，可以用uploader实现网页认证后上传了。试了一下也可以推送了。
怪的是我重新用Shell的方式上传了，没有提示错误，但还是不能推送。

**Comment by miaowm5** [comment]
我自己刚才新建了一个项目并且用这种方式部署测试了一下，测试用的是自带书籍的喷嚏图卦，正常收到了内容……

**Comment by mingde816** [comment]
现在我看日志，半个小时前尝试的几次也发送成功了。
![image](https://cloud.githubusercontent.com/assets/7845927/15703997/0342c272-281b-11e6-967d-9ff5a0af98a4.png)
我认为，也就是网页上的那个允许GAE访问的OAuth2.0认证是必须的。
因为我首次使用shell上传的时候，虽然没有提示错误，但结果的确是无法推送。等多久都是一样。。。

**Comment by miaowm5** [comment]
稍微问一句，你之前尝试的时候是北京时间下午三点前去尝试的吗？GAE 有每日的后台小时数限制，一天执行太多任务导致后台小时数超出限制之后是无法推送的，然后每天三点的时候时间重置

**Comment by mingde816** [comment]
哦，还有这样的限制啊。
不过，我昨天都没有试过，今天发现设置的定时推送没有推，才开始尝试的。
主要是北京时间今天上午。

**Comment by miaowm5** [comment]
那我也不知道是为什么了 :joy:

**Comment by mingde816** [comment]
不管怎样，还是在你另外一个issue的帮助下解决了。谢谢

**Comment by mingde816** [comment]
貌似搞清楚原因了。今天自动推送没有成功，我新建了一个project，然后就可以推送了。
如你所说，每天下午三点进行Reset，而现在已经超出配额了

![image](https://cloud.githubusercontent.com/assets/7845927/15733731/70e934aa-28bb-11e6-9e5b-e4528bd1e9cb.png)
